FROM centos:7

RUN yum update -y
RUN yum upgrade -y

# Compilers and build tools.
RUN yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
RUN yum groupinstall "Development Tools" -y
RUN yum install cmake3 gcc-c++.x86_64 make mpich-3.2-devel.x86_64 cgnslib-devel hdf5-devel hdf-devel.x86_64 blas-devel lapack-devel centos-release-scl scl-utils devtoolset-7 -y

# Change the default compilers to gcc7
# RUN echo "scl enable devtoolset-7 bash" >> /etc/skel/.bashrc

# Finds the module command, loads the mpich module
RUN echo "source /etc/profile.d/modules.sh" >> /etc/skel/.bashrc
RUN echo "module load mpi/mpich-3.2-x86_64" >> /etc/skel/.bashrc
ENV BASH_ENV "/etc/skel/.bashrc"

RUN yum install vim -y

WORKDIR /IMPACT-NO-IRAD/
ENTRYPOINT /bin/bash